version: 2.1
orbs:
  node: circleci/node@4.7.0
  aws-cli: circleci/aws-cli@2.0.3
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  - run:
      name: Swap node versions
      command: |
        set +e
        wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
        nvm install v14
        nvm alias default 14.15.5

        echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
        echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
    build:
      docker:
        - image: 'cimg/base:stable'
      steps:
        - node/install
        - checkout
        - aws-cli/setup
        - eb/setup
        - run:
            name: Install Front-End Dependencies
            command: npm run frontend:install
        - run:
            name: Front-End Build
            command: npm run frontend:build
        - run:
            name: Install Node version 12 using NVM
            command: nvm install 12
        - run:
            name: Use Node version 12
            command: nvm use 12.22.7
        - run:
            name: Install Back-End Dependencies
            command: npm run backend:install
        - run:
            name: Back-End Build
            command: npm run backend:build
        - run:
            name: Deploy Backend Application
            command: npm run backend:deploy
        - run:
            name: Deploy Frontend Application
            command: npm run frontend:deploy
