branch-defaults:
  default:
    environment: Udagrams-env-1
deploy:
  artifact: www/Archive.zip
environment-defaults:
  Udagrams-env-1:
    branch: null
    repository: null
global:
  application_name: udagrams
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
